### ISSUE TITLE
Outdoor Temperature is not being populated onto units

### ISSUE THREAD

**Issue by 1homebridge** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#402]
Hi
Since the latest update, I am unable to get the outdoor unit to populate the indoor unit temperature. I am just getting a random 8*C. Previously, all the units would show the readings from the outdoor unit when switched on and the temperature reading would turn blue when cooling and orange when heating. 
I have checked in the log and sometimes it reflects this reading, other times not, but it is never shown in the accessories both on the homebridge accessories page and in the Home App
![IMG_2552](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/90335348/5a9f3730-0bf6-4b47-b093-1a925cfa7eb1)

**Comment by mkz212** [comment]
Since 4.0.0 you can expose additional things to the AC: temperature sensor fot outdoor unit and extra switches.

Indoor unit temperature in HomeKit works like that:
- If temperature from indoor unit is available it get temp from this sensor
- If indoor sensor is not available it display hardcoded values:  8°C for heating and 30°C for cooling.


Some extra info and explanation why like that:
- Built-in temperature sensors (in the internal and external unit) give only approximate values (as the manufacturer himself indicates).
- Values from outdoor sensors are shown and updated only when the device is turned on.
- Comfort Cloud updates data only from time to time, the same plugin, which is why the temperature in the Panasonic Comfort Cloud application may be different than in HomeKit / Apple Home. You can force refresh in Panasonic app by pulling down the screen.
- For these reasons, it is not recommended to use built-in sensors for automation. Instead, it is advisable to use an external sensor.
- So what are these built-in sensors for? Internal sensor is for two simple automations that every AC have built-in: for cooling mode turn off cooling when the room temperature (internal sensor) is equal to or lower than the set, and for heating mode when it is equal or higher. Outdoor sensor is for detecting when AC should run defrost.

**Comment by 1homebridge** [comment]
I fully understand and appreciate your explanation, but just to clarify, is this plug-in no longer compatible with using the outdoor sensor to give an approximate reading because the current 8*C is lower than the 16*C cooling temp, so it shows as idle in the Home App with a green icon rather than say using the outdoor 20*C which is above the desired 16* setting so the status icon turns blue and the badge would say cooling to 16*

in order to add an additional sensor, is this wired to the AC or fully independent, and how does one link these. Is there a “manual/tutuorial” of some kind to guide me through this as I relied on that outdoor sensor that was an option in previous version. 

Thank you for your response and time.

**Comment by mkz212** [comment]
@1homebridge 

- please install 4.1.3 - it contains a fix because previously these values were the opposite. Now should work. 
- in plugin config you can select to add sensor and or switches. These are virtual only. They will be added to the main device in HomeKit.

**Comment by 1homebridge** [comment]
Thank you for that super prompt response. I just did, and I know get the 30*C which is helpful, in that it is reading higher than the 16*C cooling temperature so the unit icon is now blue and shows it is cooling rather than idle. 

Regarding additional sensors or populating the internal temperature using the outdoor temperature as in the previous version, is this possible?

Thanks

**Comment by mkz212** [comment]
@1homebridge 

I'm glad it works now. 👍

As for using outdoor temp as indoor temp, there is no such possibility. There were only problems with it. If you want outdoor temp just add outdoor sensor in plugin config.

**Comment by mkz212** [comment]
Closing. Version 4.1.3 fixes the problem. Thank you for reporting an Issue and I encourage you to take more activities in the future.
