### ISSUE TITLE
ReadableStream is not defined

### ISSUE THREAD

**Issue by aaron453980** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#496]
### Description

Encounter error Error loading plugin "homebridge-panasonic-ac-platform"
ReadableStream is not defined
Panasonic Ac Platform BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/index.js:106:19)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
Panasonic Ac Platform BridgeWARNINGNo plugins installed.
Panasonic Ac Platform BridgeLoading 1 platforms...
Panasonic Ac Platform BridgeBridge is running on port 51836.

Keeps encounter issue above, already try change node version also encounter similiar problem

### Plugin version

5.0.0

**Comment by prowlmedia** [comment]
I am getting the same thing.

**Comment by mkz212** [comment]
This plugin is for Homebridge. I don't have Hoobs so I can't verify it but in the errors in the log I don't see a single file of this plugin but the files from Hoobs so maybe it's some kind of Hoobs error?

**Comment by aaron453980** [comment]
> I am getting the same thing.

Are you using Hoobs as well?

**Comment by prowlmedia** [comment]
Is 5.x of the plugin only for homebridge 2.xI know that Hoobs is basical a skinned Homebridge code.  I  going to try  HB2 later today. Thanks On 18 Sep 2024, at 6:25 AM, aaron453980 ***@***.***> wrote:﻿

I am getting the same thing.

Are you using Hoobs as well?

**Comment by mkz212** [comment]
> Is 5.x of the plugin only for homebridge 2.xI know that Hoobs is basical a skinned Homebridge code.  I  going to try  HB2 later today. Thanks On 18 Sep 2024, at 6:25 AM, aaron453980 ***@***.***> wrote:﻿ I am getting the same thing. Are you using Hoobs as well? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

In general this plugin is for Homebridge, no matter of version. For Hoobs It can work but it doesn't have to, never tested. And for sure Hoobs and Homebridge are not a 'skinned code', there are some similarities but they are two separate projects.

So that we understand - I want to help but I don't know what the problem is at all because I don't have Hoobs.

- Does the older version of this plugin work?
- Does this plugin works on another version of Hoobs?
- Something changed when you run it without child bridge / with child bridge?

**Comment by prowlmedia** [comment]
I will do some tests my end.   I want to move to homebridge anyway.  I only used Hoobs as when it started years back,  it had a better interface for a non coder like me.  The older plugin version worked fine.  Andy On 18 Sep 2024, at 7:46 AM, mkz212 ***@***.***> wrote:﻿

Is 5.x of the plugin only for homebridge 2.xI know that Hoobs is basical a skinned Homebridge code.  I  going to try  HB2 later today. Thanks On 18 Sep 2024, at 6:25 AM, aaron453980 @.> wrote:﻿ I am getting the same thing. Are you using Hoobs as well? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

In general this plugin is for Homebridge, no matter of version. For Hoobs It can work but it doesn't have to, never tested. And for sure Hoobs and Homebridge are not a 'skinned code', there are some similarities but they are two separate projects.
So that we understand - I want to help but I don't know what the problem is at all because I don't have Hoobs.

Does the older version of this plugin work?
Does this plugin works on another version of Hoobs?
Something changed when you run it without child bridge / with child bridge?

**Comment by mkz212** [comment]
> I will do some tests my end.   I want to move to homebridge anyway.  I only used Hoobs as when it started years back,  it had a better interface for a non coder like me.  The older plugin version worked fine.  Andy On 18 Sep 2024, at 7:46 AM, mkz212 ***@***.***> wrote:﻿ Is 5.x of the plugin only for homebridge 2.xI know that Hoobs is basical a skinned Homebridge code.  I  going to try  HB2 later today. Thanks On 18 Sep 2024, at 6:25 AM, aaron453980 @.> wrote:﻿ I am getting the same thing. Are you using Hoobs as well? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> In general this plugin is for Homebridge, no matter of version. For Hoobs It can work but it doesn't have to, never tested. And for sure Hoobs and Homebridge are not a 'skinned code', there are some similarities but they are two separate projects. So that we understand - I want to help but I don't know what the problem is at all because I don't have Hoobs. Does the older version of this plugin work? Does this plugin works on another version of Hoobs? Something changed when you run it without child bridge / with child bridge? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Maybe try remove AC from cache (somewhere in Hoobs settings)?

**Comment by aaron453980** [comment]
Does this plugin works for you and stop now or never works (on Hoobs)?
>>> Works fine until this plugin updated to 5.0.0. And At the same time I update Hoobs version up for HB as well. 
Does the older version of this plugin works?
>>> Currently no. I tried older version 4.5.5 also same issue. 
Does this plugin works on another version of Hoobs?
>>> I can’t try this currently. Don’t have downgraded Hoobs. 
Something changed when you run it without child bridge / with child bridge?
>>> I am running with child bridge

I did clear the cache as well but problem still arise.

**Comment by aaron453980** [comment]
I just tested with HB, no issue there.
So most probably is Hoobs issue.
